
# 第一阶段：构建阶段（使用大而全的编译镜像）
FROM golang:1.21-alpine AS builder

# 设置代理（可选，方便国内下载依赖）
ENV GO111MODULE=on \
    GOPROXY=https://goproxy.cn,direct

# 设置工作目录
WORKDIR /app

# 1. 先复制依赖文件，利用 Docker 缓存（避免每次都要重新下载）
COPY go.mod go.sum ./
RUN go mod download

# 2. 复制源码并编译
COPY . .
# 编译：-ldflags 去掉调试信息，-s -w 可减小体积
#RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o vgate ./cmd/gate
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildvcs=false -o vapp ./cmd/app


# 第二阶段：运行阶段（使用极简的空白镜像）
FROM alpine


# 将编译好的二进制文件从 builder 复制过来  COPY 源 ，目标
COPY --from=builder /app/vapp /application/vapp

# 如果项目需要配置文件，也一并复制  COPY 源 ，目标
COPY --from=builder /app/config/config.example.yml /application/config/config.vgate.yaml


# 暴露端口（根据你的项目修改，例如 8080）
EXPOSE 8080 6789

#一定要设置工作目录   ENTRYPOINT ["/application/vGate"] 是找不到配置文件的
WORKDIR /application
# 运行
ENTRYPOINT ["./vapp"]

# 打包镜像  在控制台执行 docker build -t vapp:v1.0 -f Dockerfile_for_vapp .
# 以容器运行 docker run -d --name vapp  vapp:v1.0
